services:
  api:
    build:
      context: .
      network: host
    container_name: project-management-system
    ports:
      - 8000:8000
    volumes:
      - project-management-data:/app
    restart: unless-stopped

# volume managed by docker (docker vol)
volumes:
  project-management-data:
