[project]
name = "project-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.115.0",
    "pydantic==2.8.2",
    "pytest==8.3.2",
    "sqlalchemy>=2.0.46",
    "uvicorn[standard]==0.30.6",
]
